# wrangler.toml
name = "s6"
main = "dist/worker.mjs"
compatibility_date = "2025-10-30"
workers_dev = true

compatibility_flags = ["nodejs_compat"]

[vars]
POLY_HOST = "https://clob.polymarket.com"
CHAIN_ID = "137"

[build]
command = "npm install --no-audit --no-fund && npm run build"

[observability]
enabled = true
